# Generated by Django 5.2.8 on 2025-12-03 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['emisor', 'fecha_asignacion'], name='idx_calif_emisor_fecha'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['factor', 'fecha_asignacion'], name='idx_calif_factor_fecha'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_asignacion'], name='idx_calif_fecha'),
        ),
    ]
