# Generated by Django 5.2.8 on 2025-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_emisor_activo_calificacion_idx_calif_emisor_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialauditoria',
            name='comentario_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialauditoria',
            name='comentario_nuevo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
