# Generated by Django 5.2.8 on 2025-12-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_historialauditoria_comentario_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('ASIGNAR', 'Asignar')], default='EDITAR', max_length=10),
        ),
    ]
